const SurveysActionTypes = {
  FETCH_SURVEYS: "FETCH_SURVEYS",
  DELETE_SURVEYS_START: "DELETE_SURVEYS_START",
  DELETE_SURVEYS_FAILURE: "DELETE_SURVEYS_FAILURE",
  DELETE_SURVEYS_SUCCESS: "DELETE_SURVEYS_SUCCESS",
};

export default SurveysActionTypes;
